INSERT INTO ExamsDetails (ExamName, ExamProvider, NumHours)
VALUES
('MO-100: Microsoft Word (Word 365 and Word 2019)', 'Microsoft', 1),
('MO-101: Microsoft Word Expert (Word 365 and Word 2019)', 'Microsoft', 1),
('MO-200: Microsoft Excel (Excel 365 and Excel 2019)', 'Microsoft', 1),
('MO-201: Microsoft Excel Expert (Excel 365 and Excel 2019)', 'Microsoft', 1),
('MO-300: Microsoft PowerPoint (PowerPoint 365 and PowerPoint 2019)', 'Microsoft', 1),
('MO-400: Microsoft Outlook (Outlook 365 and Outlook 2019)', 'Microsoft', 1),
('MO-500: Microsoft Access Expert (Access and Access 2019)', 'Microsoft', 1),
('Cisco Certified Network Associates (CCNA)', 'Pearson VUE', 2),
('CompTIA A+', 'Pearson VUE', 2),
('CompTIA Network+', 'Pearson VUE', 2),
('CompTIA Security+', 'Pearson VUE', 2),
('CompTIA Project+', 'Pearson VUE', 2),
('Certified Network Defender (CND)', 'EC-Council', 1),
('Certified Ethical Hacker (CEH)', 'EC-Council', 1),
('ITIL4 Foundation', 'PeopleCert', 1),
('PRINCE2 Agile Foundation', 'PeopleCert', 1),
('PRINCE2 Agile Practitioner', 'PeopleCert', 2),
('IC3 GS6 Level 01', 'Certiport', 1),
('IC3 GS6 Level 02', 'Certiport', 1),
('IC3 GS6 Level 03', 'Certiport', 1),
('MS900 Microsoft 365 Fundamentals', 'Certiport', 1),
('AZ900 Microsoft Azure Fundamentals', 'Certiport', 1),
('AI900 Microsoft AI Fundamentals', 'Certiport', 1),
('IT Specialist - Java', 'Certiport', 1),
('IT Specialist - JavaScript', 'Certiport', 1),
('IT Specialist - Python', 'Certiport', 1),
('IT Specialist - Networking', 'Certiport', 1),
('IT Specialist - Network Security', 'Certiport', 1),
('IT Specialist - HTML and CSS', 'Certiport', 1),
('IT Specialist - Databases', 'Certiport', 1),
('IT Specialist - HTML5 Application Development', 'Certiport', 1),
('Communication Skills for Business (CSB)', 'Certiport', 1),
('Entrepreneurship & Small Business (ESB)', 'Certiport', 1),
('ACP - Visual Design using Photoshop 2021', 'Certiport', 1),
('ACP - Print & Digital Media Publication using Adobe InDesign 2021', 'Certiport', 1),
('ACP - Graphic Design & Illustration using Adobe Illustrator 2021', 'Certiport', 1),
('ACP - Web Authoring using Adobe Dreamweaver 2021', 'Certiport', 1),
('ACP - Multiplatform Animation using Adobe Animate 2021', 'Certiport', 1),
('ACP - Digital Video using Adobe Premiere Pro 2021', 'Certiport', 1),
('ACP - Visual Effects & Motion Graphics using Adobe After Effects 2021', 'Certiport', 1);
