INSERT INTO TrainingsDetails (TrainingName, TrainingType, TrainingProvider, NumHours)
VALUES
('MO-100 Word 2019/365 Associate', 'On demand', 'Microsoft', 26),
('MO-101 Word 2019/365 Expert', 'On demand', 'Microsoft', 23),
('MO-200 Excel 2019/365 Associate', 'On demand', 'Microsoft', 18),
('MO-201 Excel 2019/365 Expert', 'On demand', 'Microsoft', 23),
('MO-300 PowerPoint 2019/365 Associate', 'On demand', 'Microsoft', 26),
('MO-400 Outlook 2019/365 Associate', 'On demand', 'Microsoft', 19),
('MO-500 Access 2019/365 Expert', 'On demand', 'Microsoft', 23),
('20483CC Programming in C#', 'In-person', 'Microsoft', 40),
('20486DC Developing ASP.NET Core MVC Web Applications', 'In-person', 'Microsoft', 40),
('40410AC: JavaScript, HTML and CSS Web Development', 'In-person', 'Microsoft', 16),
('55081AC: Basic SharePoint Server 2013 Branding', 'In-person', 'Microsoft', 16),
('55048BC: No-Code SharePoint 2013-2016 Workflows With SharePoint Designer 2013', 'In-person', 'Microsoft', 24),
('55249AC: Developing with the SharePoint Framework', 'In-person', 'Microsoft', 40),
('10985CC: Introduction to SQL Databases', 'In-person', 'Microsoft', 24),
('20764CC: Administering a SQL Database Infrastructure', 'In-person', 'Microsoft', 40),
('WS-011T00-AC: Windows Server 2019 Administration', 'In-person', 'Microsoft', 40),
('20345-1BC: Administering Microsoft Exchange Server 2016/2019', 'In-person', 'Microsoft', 40),
('20345-2BC: Designing and Deploying Microsoft Exchange Server 2016/2019', 'In-person', 'Microsoft', 40),
('Cisco Certified Network Associates (CCNA)', 'In-person', 'Microsoft', 40),
('CompTIA A+', 'In-person', 'CompTIA', 40),
('CompTIA Network+', 'In-person', 'CompTIA', 40),
('CompTIA Security+', 'In-person', 'CompTIA', 40),
('CompTIA Project+', 'In-person', 'CompTIA', 40),
('Certified Network Defender (CND)', 'In-person', 'EC-Council', 40),
('Certified Ethical Hacker (CEH)', 'In-person', 'EC-Council', 40),
('ITIL4 Foundation', 'In-person', 'PeopleCert', 24),
('PRINCE2 Agile Foundation', 'In-person', 'PeopleCert', 24),
('PRINCE2 Agile Practitioner', 'In-person', 'PeopleCert', 16),
('IC3 GS6 Level 01', 'On demand', 'Certiport', 23),
('IC3 GS6 Level 02', 'On demand', 'Certiport', 24),
('IC3 GS6 Level 03', 'On demand', 'Certiport', 22),
('MS900 Microsoft 365 Fundamentals', 'On demand', 'Certiport', 17),
('AZ900 Microsoft Azure Fundamentals', 'On demand', 'Certiport', 18),
('AI900 Microsoft AI Fundamentals', 'On demand', 'Certiport', 25),
('IT Specialist - Java', 'On demand', 'Certiport', 17),
('IT Specialist - JavaScript', 'On demand', 'Certiport', 29),
('IT Specialist - Python', 'On demand', 'Certiport', 21),
('IT Specialist - Networking', 'On demand', 'Certiport', 25),
('IT Specialist - Network Security', 'On demand', 'Certiport', 32),
('IT Specialist - HTML and CSS', 'On demand', 'Certiport', 32),
('IT Specialist - Databases', 'On demand', 'Certiport', 16),
('IT Specialist - HTML5 Application Development', 'On demand', 'Certiport', 24),
('Communication Skills for Business (CSB)', 'On demand', 'Certiport', 22),
('Entrepreneurship & Small Business (ESB)', 'On demand', 'Certiport', 14),
('ACP - Visual Design using Photoshop 2021', 'On demand', 'Adobe', 17),
('ACP - Print & Digital Media Publication using Adobe InDesign 2021', 'On demand', 'Adobe', 23),
('ACP - Graphic Design & Illustration using Adobe Illustrator 2021', 'On demand', 'Adobe', 22),
('ACP - Web Authoring using Adobe Dreamweaver 2021', 'On demand', 'Adobe', 21),
('ACP - Multiplatform Animation using Adobe Animate 2021', 'On demand', 'Adobe', 25),
('ACP - Digital Video using Adobe Premiere Pro 2021', 'On demand', 'Adobe', 21),
('ACP - Visual Effects & Motion Graphics using Adobe After Effects 2021', 'On demand', 'Adobe', 34);
